version: '3.4'

services:

  sqldata:
      volumes:
        - ./db:/var/opt/mssql/data 
      image: mcr.microsoft.com/mssql/server:2019-latest
      environment:
          - SA_PASSWORD=Numsey#2022
          - ACCEPT_EULA=Y
      ports:
          - "1450:1433"


  studioweb.api:
    image: ${DOCKER_REGISTRY-}studiowebapi
    build:
      context: .
      dockerfile: src/StudioWeb.API/Dockerfile



  JWT:
    image: ${DOCKER_REGISTRY-}jwt
    build:
      context: .
      dockerfile: src/JWT/Dockerfile
