version: '3.4'

networks:
  backend:

services:

  sqldata:
      volumes:
        - ./db:/var/opt/mssql/data 
      image: mcr.microsoft.com/mssql/server:2019-latest
      environment:
          - SA_PASSWORD=Numsey#2022
          - ACCEPT_EULA=Y
      networks:
          - backend
      ports:
          - "1450:1433"


  studioweb.api:
    image: ${DOCKER_REGISTRY-}studiowebapi
    build:
      context: .
      dockerfile: src/StudioWeb.API/Dockerfile
    environment:
      - DB_HOST=sqldata
      - DB_NAME=studioweb
      - DB_SA_PASSWORD=Numsey#2022
    networks:
      - backend


  JWT:
    image: ${DOCKER_REGISTRY-}jwt
    build:
      context: .
      dockerfile: src/JWT/Dockerfile
    environment:
      - DB_HOST=sqldata
      - DB_NAME=jwts
      - DB_SA_PASSWORD=Numsey#2022
    networks:
      - backend
